// <auto-generated />
using G_Stock_Vente.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace G_Stock_Vente.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220406222914_CreateDB")]
    partial class CreateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("G_Stock_Vente.Models.General", b =>
                {
                    b.Property<int>("reference")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("alerteJour")
                        .HasColumnType("int");

                    b.Property<string>("appNom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("devise")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("reference");

                    b.ToTable("General");
                });
#pragma warning restore 612, 618
        }
    }
}
